---
dock_autohide: true
dock_autohide_delay: 0

dock_tilesize: 63

dock_magnification: true
dock_largesize: 85

# possible values: left, right, bottom
dock_orientation: "left"

dock_springload: true

dock_remove_items:
  - Siri
  - Launchpad
  - Safari
  - Mail
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

dock_add_items:
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 1
  - name: Sublime Text
    path: "/Applications/Sublime\ Text.app"
    pos: 2
  # - name: Google Chrome
  #   path: "/Applications/Google\ Chrome.app"
  #   pos: 3
