---
- hosts: all
  connection: local

  vars_files:
    - vars/main.yml

  roles: []

  tasks:
    - name: Say hi
      osx_say:
        msg: 'Hello there'
        voice: Samantha
      delegate_to: localhost
