---
- hosts: all
  connection: local

  pre_tasks:
    - stat: path="{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      register: user_override

    - include_vars:
        file: "{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      when: user_override.stat.exists

  roles:
    - user
  