---
- hosts: all
  connection: local

  pre_tasks:
    - set_fact:
        user_home_dir: "/Users/{{ansible_user_id}}"
        
    - stat: path="{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      register: user_override

    - include_vars:
        file: "{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      when: user_override.stat.exists

    - stat: path="{{ playbook_dir }}/secrets.yml"
      register: vault_file

    - include_vars:
        file: "{{ playbook_dir }}/secrets.yml"
      when: vault_file.stat.exists

  roles:
    # - profile
    - dock

  tasks:
    - name: cleanup temp files
      file:
        path: "{{ onepass_temp_dir }}"
        state: absent
      when: onepass_temp_dir is defined