---
- hosts: all
  connection: local

  pre_tasks:
    - stat: path="{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      register: user_override

    - include_vars:
        file: "{{ playbook_dir }}/users/{{ ansible_user_id }}.yml"
      when: user_override.stat.exists

    - stat: path="{{ playbook_dir }}/secrets.yml"
      register: vault_file

    - include_vars:
        file: "{{ playbook_dir }}/secrets.yml"
      when: vault_file.stat.exists

  roles:
    # - profile
    - onepass

  tasks:
    - pause:
    - name: cleanup temp files
      file:
        path: "{{ onepass_temp_dir }}"
        state: absent
      when: onepass_temp_dir is defined