---
# process each item based on category
- name: Process 'document' category
  include_tasks: document.yml document_item="{{ onepass_item }}"
  when: onepass_item.templateUuid == onepass_category_document

- name: Process 'software license' category
  include_tasks: license.yml license_item="{{ onepass_item }}"
  when: onepass_item.templateUuid == onepass_category_license
