---
- name: Install UI
  homebrew_cask:
    name: 1password
    state: present

- name: Install command line
  homebrew_cask:
    name: 1password-cli
    state: present

- name: Get a session token
  command: op signin {{ onepass_subdomain|quote }} {{ onepass_email|quote}} {{ onepass_key|quote }} {{ onepass_master_pass|quote }} --output=raw
  register: onepass_session_token
- set_fact:
    onepass_session_token: "{{ onepass_session_token.stdout }}"

- name: Create temp folder
  tempfile:
    prefix: _ansible
    state: directory
  register: onepass_temp_dir
- set_fact:
    onepass_temp_dir: "{{ onepass_temp_dir.path }}"

# - debug:
#     var: onepass_temp_dir
# - pause:


- name: List items in the vault
  command: op list items --vault={{ onepass_vault }} --session={{ onepass_session_token }}
  register: item_list

- name: Filter items tagged with user-id
  include_tasks: download.yml onepass_item="{{ outer_item }}"
  when: ansible_user_id in outer_item.overview.tags
  with_items: "{{ item_list.stdout }}"
  loop_control:
    loop_var: outer_item