---
- name: Tap cask fonts
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: Install system fonts
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'fontdir=/Library/Fonts'
  with_items: "{{ system_fonts }}"

- name: Install user fonts
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_fonts }}"